version: 2
updates:
  - package-ecosystem: docker
    directory: /
    allow:
      - dependency-name: 'jupyter/julia-notebook'
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'Update Julia notebook base'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
